DROP TABLE IF EXISTS Products CASCADE;


CREATE TABLE Products (
id INT PRIMARY KEY,
series VARCHAR(50) NOT NULL,
model VARCHAR(50) NOT NULL, 
price INT NOT NULL,
rating NUMERIC NOT NULL,
measurements VARCHAR(400) NOT NULL,
weight NUMERIC NOT NULL,
colour_name VARCHAR(50) NOT NULL,
url VARCHAR(150) NOT NULL
);